### ISSUE TITLE
Conexão Banco com Java

### ISSUE THREAD

**Issue by nathalietaylor** [nathalietaylor/BibliotecaDigital#3]

**Comment by katerine-dev** [comment]
Foi criado uma conexão em protótipo: [classe database](https://github.com/katerine-dev/prototipoBD/blob/main/src/main/java/prototipodb/Database.java)

Descobri que a conexão precisa ser um classe chamada no [main](https://github.com/katerine-dev/prototipoBD/blob/main/src/main/java/prototipodb/Main.java) 

Como vamos usar o MySQL vamos precisar de um gerenciador de dependência, estou utilizando o Maven nesse repositório para que o projeto tenho o arquivo POM.xml (onde declaramos as dependências). Vamos ter que conversar sobre o formato do projeto já criado. 

- [Script](https://github.com/katerine-dev/prototipoBD/blob/main/sql/BDBiblioteca.sql) de teste para DB em SQL. 

Outra tarefa será necessária: 

-  [ ] Nessa mesma classe database precisamos criar os métodos de interação com a DB.

**Comment by katerine-dev** [comment]
[Pronto!](https://github.com/katerine-dev/prototipoBD/blob/main/src/main/java/prototipodb/database/Database.java)
